[tool.poetry]
name = "Deep Brain Structural Connectivity"
version = "0.1.0-pre.1"
description = "Snakebids app for mapping the subcortical connectome"
authors = [
    "Jason Kai <tkai@uwo.ca>",
    "Tristan Kuehn",
    "Ali R. Khan",
    "Roy A.M. Haast",
    "Jonathan C. Lau",
    ]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
snakebids = "^0.6.0"
nibabel = "^3.2.2"
numpy = "^1.22.3"
scipy = "^1.8.0"

[tool.poetry.group.dev.dependencies]
flake8 = "4.0"
pytest-console-scripts = "1.2"
pytest = "^7.0.1"
black = "^22.1.0"
pylint = "^2.12.2"
isort = "^5.10.1"
poethepoet = "^0.13.1"
pre-commit = "^2.17.0"
snakefmt = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
setup = "pre-commit install"
isort = "isort dbsc/*.py"
black = "black dbsc -l 79"
snakefmt = "snakefmt dbsc"
quality = ["isort", "black", "snakefmt"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.snakefmt]
include = '\.smk$|^Snakefile'
