[tool.poetry]
name = "scattr"
version = "0.1.2"
description = "Snakebids app for structural connectivity between targeted regions"
authors = [
    "Jason Kai <tkai@uwo.ca>",
    "Tristan Kuehn",
    "Ali R. Khan",
    "Roy A.M. Haast",
    "Jonathan C. Lau",
    ]
readme = "README.md"
packages = [
    { include = "scattr" }
]

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
snakebids = "^0.7.0"
nibabel = "^3.2.2"
numpy = "^1.22.3"
scipy = "^1.8.0"
labelmerge = {git = "https://github.com/khanlab/labelmerge.git", rev = "v0.4.3"}

[tool.poetry.group.dev.dependencies]
flake8 = "4.0"
pytest-console-scripts = "1.2"
pytest = "^7.0.1"
black = "^22.1.0"
pylint = "^2.12.2"
isort = "^5.10.1"
poethepoet = "^0.13.1"
pre-commit = "^2.17.0"
snakefmt = "^0.6.1"
yamlfix = "^1.1.0"

[tool.poetry.scripts]
scattr = 'scattr.run:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
setup = "pre-commit install"
yamlfix = { shell = "find . -type f \\( -iname \\*.yaml -o -iname \\*.yml ! -iname snakemake* ! -iname snakebids* \\) -exec yamlfix {} \\;" }
yamlfix-check = { shell = "find . -type f \\( -iname \\*.yaml -o -iname \\*.yml ! -iname snakemake* ! -iname snakebids* \\) -exec yamlfix --check {} \\;" }
isort = "isort scattr"
isort-check = "isort -c scattr"
black = "black scattr"
black-check = "black --check scattr"
flake8 = "flake8 scattr"
snakefmt = "snakefmt scattr"
snakefmt-check = "snakefmt --check scattr"
quality = ["yamlfix", "isort", "black", "flake8", "snakefmt"]
quality-check = [
    "yamlfix-check",
    "isort-check",
    "black-check",
    "flake8",
    "snakefmt-check",
]
test_base = { shell = "python ./scattr/run.py ./test/data/bids ./test/data/derivatives/ participant --fs-license ./test/.fs_license -np --force-output" }
test_freesurfer = { shell = "python ./scattr/run.py ./test/data/bids test/data/derivatives/ participant --freesurfer_dir ./test/data/derivatives/freesurfer --fs-license ./test/.fs_license -np --force-output" }
test_responsemean = { shell = "python ./scattr/run.py ./test/data/bids test/data/derivatives/ participant --responsemean_dir ./test/data/derivatives/mrtrix/avg --fs-license ./test/.fs_license -np --force-output" }
test_dwi = { shell = "python ./scattr/run.py ./test/data/bids_nodwi test/data/derivatives/ participant --dwi_dir ./test/data/derivatives/prepdwi --fs-license ./test/.fs_license -np --force-output" }
test_labelmerge = { shell = "python ./scattr/run.py ./test/data/bids test/data/derivatives/ participant --labelmerge_base_dir ./base_dir --labelmerge_overlay_dir ./overlay_dir --skip_brainstem --skip_thal_seg --fs-license ./test/.fs_license -np --force-output" }
test_skip_labelmerge = { shell = "python ./scattr/run.py ./test/data/bids test/data/derivatives/ participant --skip_labelmerge --skip_brainstem --skip_thal_seg --fs-license ./test/.fs_license -np --force-output" }
test = ["test_base", "test_freesurfer", "test_responsemean", "test_dwi", "test_labelmerge", "test_skip_labelmerge"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 79

[tool.snakefmt]
line_length = 79
include = '\.smk$|^Snakefile'
